import Link from 'next/link';
import {
  ArrowRight, Users, Sparkles, Palette, Code2, Plug,
  Wallet, LifeBuoy, LineChart, CheckCircle2,
} from 'lucide-react';
import { Navbar } from '@/components/marketing/navbar';
import { Footer } from '@/components/marketing/footer';

export const metadata = {
  title: 'Adyapan Connect Partner | Add WhatsApp Marketing to your Services',
  description: 'Become an Adyapan Connect Partner. Add the smartest WhatsApp engagement platform to your offerings and create a new revenue stream.',
};

const partnerModels = [
  { icon: Users, title: 'Affiliate Commission Model', desc: 'Earn 20% recurring affiliate commission on each referral (min payout of ₹999).' },
  { icon: Sparkles, title: 'Prime Plus Partner', desc: 'Earn higher recurring affiliate commission across all revenue streams.' },
  { icon: Palette, title: 'White-Labelled Solution', desc: 'Resell the platform under your own branding, with your logo and sub-domain.' },
  { icon: Code2, title: 'Get Access to APIs', desc: 'Build your own platform on top of our platform and partner APIs.' },
  { icon: Plug, title: 'Integration Partnership', desc: 'Integrate Adyapan Connect into your platform and let clients send WhatsApp messages from your dashboard.' },
];

const deepDive = [
  {
    title: 'Affiliate Partner',
    body: 'Turn your network into income. Share your referral link, introduce businesses to Adyapan Connect, and earn 20% commission on every purchase for as long as they stay. No support worries — we handle onboarding and setup.',
    image: 'https://images.unsplash.com/photo-1556155092-490a1ba16284?auto=format&fit=crop&w=800&q=80',
  },
  {
    title: 'Prime Plus Partner',
    body: 'Earn higher recurring commissions not just on plans sold, but also on Ad Credits and WhatsApp Conversation Credits. Every sale and every conversation helps you grow your revenue faster than ever.',
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80',
  },
  {
    title: 'White-Labelled WhatsApp Solution',
    body: 'Want to launch your own WhatsApp Marketing platform? Get the Adyapan Connect platform under your brand name — custom domain, logo, pricing, everything. We manage the backend, while you own the customer experience.',
    image: 'https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?auto=format&fit=crop&w=800&q=80',
  },
  {
    title: 'Direct APIs Partnership',
    body: 'Build your own WhatsApp Marketing platform on top of our rock-solid WhatsApp APIs. Ideal if you have a tech team that can build a custom WhatsApp solution on top of the Official WhatsApp APIs.',
    image: 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&w=800&q=80',
  },
  {
    title: 'Integration Partnership',
    body: 'Integrate Adyapan Connect into your platform and enable clients to send WhatsApp messages directly from your dashboard — making your product more powerful with seamless WhatsApp automation.',
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=800&q=80',
  },
];

const stats = [
  { value: '6000+', label: 'Partners' },
  { value: '200Cr+', label: 'Revenue Generated by Partners' },
  { value: '20+', label: 'Countries' },
  { value: '30+', label: 'Tech Partners' },
];

const benefits = [
  { icon: Wallet, title: 'Monthly Payouts', desc: 'Get your earned commission every month.' },
  { icon: LifeBuoy, title: 'Onboarding Support', desc: 'Our team helps you onboard customers easily.' },
  { icon: LineChart, title: 'Tracking Dashboard', desc: 'Track all your conversions via our affiliate dashboard.' },
];

export default function PartnerPage() {
  return (
    <main className="min-h-screen bg-white">
      <Navbar />

      {/* Hero */}
      <section className="bg-gradient-to-b from-green-50 to-white px-4 py-20 sm:px-6 lg:px-8">
        <div className="mx-auto grid max-w-6xl items-center gap-12 lg:grid-cols-2">
          <div className="text-center lg:text-left">
            <span className="inline-block rounded-full bg-green-100 px-4 py-1.5 text-xs font-semibold uppercase tracking-wide text-green-700">
              Create a new revenue stream
            </span>
            <h1 className="mt-6 text-4xl font-bold leading-tight text-gray-900 sm:text-5xl">
              Add WhatsApp Marketing to your services
            </h1>
            <p className="mt-5 max-w-xl text-lg text-gray-600 lg:mx-0">
              Add the smartest WhatsApp Engagement &amp; Click-to-WhatsApp Ads platform to your offerings and start earning with every referral.
            </p>
            <div className="mt-8 flex flex-col items-center justify-center gap-3 sm:flex-row lg:justify-start">
              <Link href="/signup" className="flex items-center gap-2 rounded-lg bg-green-500 px-6 py-3 text-sm font-semibold text-white shadow-sm transition-colors hover:bg-green-600">
                Become a Partner <ArrowRight className="h-4 w-4" />
              </Link>
              <Link href="/pricing" className="rounded-lg border border-gray-300 px-6 py-3 text-sm font-semibold text-gray-700 transition-colors hover:bg-gray-50">
                View Pricing
              </Link>
            </div>
          </div>
          <div className="relative">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src="https://images.unsplash.com/photo-1552581234-26160f608093?auto=format&fit=crop&w=900&q=80"
              alt="Partners collaborating on a marketing strategy"
              className="w-full rounded-3xl object-cover shadow-xl"
            />
            <div className="absolute -bottom-5 -left-5 hidden rounded-2xl bg-white px-5 py-4 shadow-lg sm:block">
              <p className="text-2xl font-bold text-green-600">20%</p>
              <p className="text-xs text-gray-500">Recurring commission</p>
            </div>
          </div>
        </div>
      </section>

      {/* Partner Models */}
      <section className="px-4 py-16 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-6xl">
          <div className="text-center">
            <h2 className="text-3xl font-bold text-gray-900">Our Partner Models</h2>
            <p className="mx-auto mt-3 max-w-2xl text-gray-600">
              Multiple partner models for agencies, freelancers, marketplaces, businesses and promoters.
            </p>
          </div>
          <div className="mt-12 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
            {partnerModels.map(m => (
              <div key={m.title} className="rounded-2xl border border-gray-100 bg-white p-6 shadow-sm transition-shadow hover:shadow-md">
                <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-green-100">
                  <m.icon className="h-5 w-5 text-green-600" />
                </div>
                <h3 className="mt-4 text-lg font-semibold text-gray-900">{m.title}</h3>
                <p className="mt-2 text-sm leading-relaxed text-gray-600">{m.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Deep dive */}
      <section className="bg-gray-50 px-4 py-16 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-6xl">
          <h2 className="text-center text-3xl font-bold text-gray-900">
            Deep dive into Adyapan Connect Partner Models
          </h2>
          <div className="mt-12 space-y-14">
            {deepDive.map((d, i) => (
              <div key={d.title} className="grid items-center gap-8 md:grid-cols-2">
                <div className={i % 2 === 1 ? 'md:order-2' : ''}>
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img
                    src={d.image}
                    alt={d.title}
                    className="h-64 w-full rounded-2xl object-cover shadow-md"
                  />
                </div>
                <div className={i % 2 === 1 ? 'md:order-1' : ''}>
                  <h3 className="text-2xl font-semibold text-gray-900">{d.title}</h3>
                  <p className="mt-3 leading-relaxed text-gray-600">{d.body}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Why partner — stats */}
      <section className="px-4 py-16 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-6xl">
          <h2 className="text-center text-3xl font-bold text-gray-900">Why Partner with Adyapan Connect?</h2>
          <div className="mt-12 grid grid-cols-2 gap-8 lg:grid-cols-4">
            {stats.map(s => (
              <div key={s.label} className="text-center">
                <p className="text-4xl font-bold text-green-600">{s.value}</p>
                <p className="mt-2 text-sm text-gray-600">{s.label}</p>
              </div>
            ))}
          </div>
          <p className="mt-10 text-center text-gray-500">
            Trusted by 210,000+ businesses across 68+ countries
          </p>
        </div>
      </section>

      {/* Benefits */}
      <section className="bg-gray-50 px-4 py-16 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-6xl">
          <h2 className="text-center text-3xl font-bold text-gray-900">Grow with Adyapan Connect</h2>
          <p className="mt-3 text-center text-gray-600">Become an Adyapan Connect Partner</p>
          <div className="mt-12 grid gap-6 md:grid-cols-3">
            {benefits.map(b => (
              <div key={b.title} className="rounded-2xl border border-gray-100 bg-white p-8 text-center">
                <div className="mx-auto flex h-12 w-12 items-center justify-center rounded-xl bg-green-100">
                  <b.icon className="h-6 w-6 text-green-600" />
                </div>
                <h3 className="mt-4 text-lg font-semibold text-gray-900">{b.title}</h3>
                <p className="mt-2 text-sm text-gray-600">{b.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Final CTA */}
      <section className="px-4 py-20 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-4xl rounded-3xl bg-gradient-to-r from-green-600 to-emerald-600 px-8 py-14 text-center shadow-lg">
          <h2 className="text-3xl font-bold text-white">Become a Partner Today</h2>
          <p className="mx-auto mt-4 max-w-xl text-green-50">
            Sign up now, share your link, and start getting partner benefits instantly!
          </p>
          <div className="mt-8 flex flex-wrap items-center justify-center gap-x-8 gap-y-3">
            {['Monthly Payouts', 'Onboarding Support', 'Tracking Dashboard'].map(item => (
              <span key={item} className="flex items-center gap-2 text-sm font-medium text-green-50">
                <CheckCircle2 className="h-4 w-4" /> {item}
              </span>
            ))}
          </div>
          <Link href="/signup" className="mt-8 inline-flex items-center gap-2 rounded-lg bg-white px-8 py-3 text-sm font-semibold text-green-700 shadow-sm transition-transform hover:scale-[1.02]">
            Become a Partner <ArrowRight className="h-4 w-4" />
          </Link>
        </div>
      </section>

      <Footer />
    </main>
  );
}
