export const APP_CONFIG = {
  name: 'Adyapan Connect',
  tagline: 'Connect. Automate. Engage. Grow.',
  description: 'AI-Powered WhatsApp Business Messaging, CRM & Automation SaaS',
  domain: 'connect.adyapan.com',
  supportEmail: 'support@adyapanconnect.com',
  docsUrl: 'https://docs.adyapanconnect.com',
  apiVersion: 'v1',
  brand: {
    primaryColor: '#16a34a',
    secondaryColor: '#15803d',
    accentColor: '#22c55e',
  },
  plans: {
    STARTER: { name: 'Starter', priceMonthly: 999, priceAnnual: 9990 },
    GROWTH: { name: 'Growth', priceMonthly: 2499, priceAnnual: 24990 },
    BUSINESS: { name: 'Business', priceMonthly: 5999, priceAnnual: 59990 },
    ENTERPRISE: { name: 'Enterprise', priceMonthly: 0, priceAnnual: 0 },
  },
  defaultPlanLimits: {
    STARTER: {
      contacts: 5000,
      agents: 3,
      whatsappNumbers: 1,
      campaigns: 10,
      apiRequestsPerMonth: 10000,
      aiMessagesPerMonth: 500,
      automations: 5,
      storageGb: 2,
      teamMembers: 5,
    },
    GROWTH: {
      contacts: 25000,
      agents: 10,
      whatsappNumbers: 3,
      campaigns: 50,
      apiRequestsPerMonth: 100000,
      aiMessagesPerMonth: 5000,
      automations: 25,
      storageGb: 10,
      teamMembers: 15,
    },
    BUSINESS: {
      contacts: 100000,
      agents: 30,
      whatsappNumbers: 10,
      campaigns: -1,
      apiRequestsPerMonth: 500000,
      aiMessagesPerMonth: 25000,
      automations: -1,
      storageGb: 50,
      teamMembers: 50,
    },
    ENTERPRISE: {
      contacts: -1,
      agents: -1,
      whatsappNumbers: -1,
      campaigns: -1,
      apiRequestsPerMonth: -1,
      aiMessagesPerMonth: -1,
      automations: -1,
      storageGb: -1,
      teamMembers: -1,
    },
  },
  whatsapp: {
    graphApiVersion: 'v19.0',
    graphApiUrl: 'https://graph.facebook.com',
    maxRetries: 3,
    retryDelay: 1000,
    rateLimitPerSecond: 80,
    messagingWindowHours: 24,
  },
  queue: {
    campaignConcurrency: 5,
    messageConcurrency: 10,
    webhookConcurrency: 10,
    defaultJobAttempts: 3,
    backoffDelay: 2000,
  },
};

export const ROLES_PERMISSIONS = {
  SUPER_ADMIN: ['*'],
  PLATFORM_ADMIN: ['admin.*', 'tenant.*'],
  TENANT_OWNER: [
    'campaign.*', 'conversation.*', 'contact.*', 'template.*',
    'analytics.*', 'billing.*', 'developer.*', 'team.*',
    'whatsapp.*', 'settings.*', 'crm.*', 'chatbot.*',
    'workflow.*', 'ai_agent.*', 'audit_log.view',
  ],
  TENANT_ADMIN: [
    'campaign.*', 'conversation.*', 'contact.*', 'template.*',
    'analytics.view', 'billing.view', 'developer.*', 'team.*',
    'whatsapp.view', 'settings.*', 'crm.*', 'chatbot.*', 'workflow.*',
  ],
  MANAGER: [
    'campaign.*', 'conversation.*', 'contact.*', 'template.*',
    'analytics.view', 'crm.*', 'team.manage',
  ],
  AGENT: ['conversation.view', 'conversation.reply', 'conversation.assign', 'contact.view', 'contact.create'],
  CAMPAIGN_MANAGER: ['campaign.*', 'contact.view', 'template.view', 'analytics.view'],
  ANALYST: ['analytics.*', 'campaign.view', 'contact.view', 'conversation.view'],
  DEVELOPER: ['developer.*', 'whatsapp.view'],
  BILLING_MANAGER: ['billing.*'],
  VIEWER: ['campaign.view', 'conversation.view', 'contact.view', 'analytics.view'],
};
